includePaths: []
stylesheets:
javascripts:
output_dir: public
base_url: https://zaiste.net
ga:
  domain: zaiste.net
  site_id: UA-20458791-1
deploy:
  server: nu02
  path: /srv/www/zaiste.net/html
blog:
  prefix: none

directory: new-zaiste.net
