base_url = "https://zaiste.net"
compile_sass = true
highlight_code = true
highlight_theme = "classic-modified"
build_search_index = false

title = "Zaiste Programming"
description = """
Zaiste Programming is a personal website by Jakub Neander about Java, Ruby, Python, JavaScript,
Node.js, Clojure, Dart, Flutter and more.
"""

taxonomies = [ {name = "topics", rss = true} ]

[extra]
image_url = ""
image_type = ""
image_width = ""
image_height = ""


